{% set name = "bash_kernel" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0183d53e360ff9b68471052a9a289a81621732516b034e278e9720b5d15a162b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m flit install --deps none
    - {{ PYTHON }} -m bash_kernel.install --prefix {{ PREFIX }}

requirements:
  host:
    - pip
    - python
    - flit
    # flit tries to validate the install on windows.
    - pexpect
    - ipykernel
  run:
    - __unix
    - python >=3
    - ipykernel
    - pexpect
    - bash

test:
  imports:
    - bash_kernel
  commands:
    - jupyter kernelspec list | grep bash
    - jupyter run --kernel=bash command.sh
  files:
    - command.sh

about:
  home: https://github.com/takluyver/bash_kernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for bash
  doc_url: https://github.com/takluyver/bash_kernel
  dev_url: https://github.com/takluyver/bash_kernel

extra:
  recipe-maintainers:
    - BoPeng
    - takluyver
    - blink1073
