{% set name = "bash_kernel" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ed5a0a416c418d1d751e71505bd6c889e12157444b50c4287a685da775c28ca

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m flit install --deps none
    - {{ PYTHON }} -m bash_kernel.install --prefix {{ PREFIX }}

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit
    # flit tries to validate the install on windows.
    - pexpect
    - ipykernel
    - filetype
  run:
    - __unix
    - python >={{ python_min }}
    - ipykernel
    - pexpect
    - bash
    - filetype

test:
  requires:
    - python {{ python_min }}
  imports:
    - bash_kernel
  commands:
    - jupyter kernelspec list | grep bash
    - jupyter run --kernel=bash command.sh
  files:
    - command.sh

about:
  home: https://github.com/takluyver/bash_kernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for bash
  doc_url: https://github.com/takluyver/bash_kernel
  dev_url: https://github.com/takluyver/bash_kernel

extra:
  recipe-maintainers:
    - BoPeng
    - takluyver
    - blink1073
