{% set name = "bash_kernel" %}
{% set version = "0.7.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a08c84eddd8179de5234105821fd5cc210015671a0bd3cd0bc4f631c475e1670

build:
  number: 1
  # doesn't give the correct path for Windows in the json file
  # https://github.com/conda-forge/staged-recipes/issues/9465
  # noarch: python
  skip: True # [py==27]
  # Windows needs additional dependencies that aren't fully working on
  # skip: True # [win]
  script:
    - {{ PYTHON }} -m flit install --deps none
    - {{ PYTHON }} -m bash_kernel.install --prefix {{ PREFIX }}

requirements:
  host:
    - pip
    - python
    - flit
    - ipykernel
  run:
    - python
    - ipykernel
    - pexpect
    - bash  # [unix]
    - m2-bash  # [win]

test:
  imports:
    - bash_kernel
  commands:
    - jupyter kernelspec list | grep bash
    - jupyter run --kernel=bash command.sh
  files:
    - command.sh

about:
  home: https://github.com/takluyver/bash_kernel
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "A Jupyter kernel for bash"
  doc_url: https://github.com/takluyver/bash_kernel
  dev_url: https://github.com/takluyver/bash_kernel

extra:
  recipe-maintainers:
    - BoPeng
    - takluyver
    - blink1073
