travis:
  secure:
    BINSTAR_TOKEN: tkxfrDlj9Cq+jYaGQFUVZKxVF3dc+WeeqIZAK/1pLw/iKV+tjKunKFxt7ga6eHpvJZ3M01papjth3m9sGf9s2Qv+Vcix2O8jI3/Uuo0UfVuH08iNhBgpbTq1leZuu+56cIeLrD+YjW9xfCbIW4FLNK5YmRQIa4FnMNgveGkSbrEwpmDqWAnITQrUCi4SANijCcp7GOMh1CMxMy790atXAbp/avpelyWqoCuEfcVAQRifEI88xjwP+lCmqzbJuonSW9tf7cqzIxT/A3WU6WpsKc2YHrhwjxdQldC+Ot4O96kvgcMAtstZX57espqb/qUCcyNRityn5JWWs8dTuUBpamyf/ZdG8Y3XOSgveOLnctPSRLJplylDFluCucK3CiyYK68lLuWqwiAH3uHdm5DkvV1H3FyfvoR3/3MiGYc26QbyUrrr8sbMfYWewaHzFJ5S2U0Icrfs5qIqgcq6B1yDh2yaNLPP6j8Uojda+IWZzftdwAMOc9KYdoXDKr2w3+tHqvDawnXCNCu0PBXnVQY5fkF+n1+FL6S2alj4x6zFOjihT5McPUW5mZzOWTehR+7C8aqUYumfFpFadi3taVPuoz/astP00v9ENAqpuMvo9YI5KiaC6+uH9FPncdJhB8gKSnyoBFJi16ncbNProJAI1dDbZx4Tr0RGvsQTDtDbjVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
