travis:
  secure:
    BINSTAR_TOKEN: eVS5cUu8KotQxnC6rvGAp3IXGbsBS1ooTjr/qEN6KiacsmCouL+qNZlDjA6voC/DkoRoEa5e48iIxxQnhGlcnrqrp37ch6eJdMforBTQNrSUMkYZ5/9crJeA+NrPRpLDg30fx5CzGBGksYBloIP9o6LKCSGB9ucWaihqg/BHi2zWPsM7C48woTcNjs3MuLOwI5J/xoWXXlv+o+fh2c6br01I2ffoPfi4BOzeLRUjhSGAKZL6WBNhx2QmiQ8fbZrKHax7sqKdxQPq0XgKcyjhViu2uauIyX3XVVOjz/JVkn4W69JS0ak+5exdXsPp3KQag+KSRDDZZt0yp2b/oYssUELGr9zWksXjRYDXDXwcnzrpzxBbYCGWBq5yr2IZ7hHPp80vK0UgVlH3Tn+ua5hFBBuQvEmzvx1saCMihRnPviAUusooV8aPDY1P+2zMoYCjpxsYg4VV7YnL8tUpEJ25PP8SX/NPAYkPefEANLi5tYpP/3POYt9hOWIqHeN0PNaWnIuo/lUuBzqRcm0raE1Qvk/cJp20jcuGdaIb51NKCQGt2O/bDRnFWHQe92E4I1fT/d9snGN4/S+dwD2uzQho6Yxcp3BZocT4gNtrHdfLONJaHCLvFma6fTsjNR33vTGAYk0IqG2vFxJ8/UflcpgsVMJTAiQz2mLeURJx+JIYvMk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
